### ISSUE TITLE
[TASK] Main Menu Update

### ISSUE THREAD

**Issue by MerseyAnimalHub-BM** [MerseyAnimalHub/Website#14]
**URL**
All Pages

**Summary of task**
Update Main Menu with new links and updated broken links.

**Task to-do list**

- [x] Add New Menu Categorie "Organization"
- [x] ~~Add Forms Page as "Forms" under Organization~~
- [x] Add Pet Care 
- [x] Add Out Of Hours to Organization Categorie

**Additional context**

**Comment by MerseyAnimalHub-BM** [comment]
We have removed Forms Page from the list as it was moved to Release 0.3 #13

**Comment by MerseyAnimalHub-BM** [comment]
Completed
