### ISSUE TITLE
[FEATURE REQUEST] Animals Ready For Adoption Page

### ISSUE THREAD

**Issue by MerseyAnimalHub-BM** [MerseyAnimalHub/Website#23]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A page connecting to our pet database showing animals available for adoption.

**Describe alternatives you've considered**
N/A

**Additional context**
Update the Adoption Page to reflect the new page.

**Tasks**

- [x] Create Animal Adoption Page.
- [x] Add our database to the page.
- [x] Add a link on adoption page to the Animal Ready For Adoption Page. #24 
- [x] Add a link on the main menu under services. #25

**Comment by MerseyAnimalHub-BM** [comment]
Completed and Released to Current Release https://github.com/MerseyAnimalHub/Website/milestone/2
